name: Delete Inactive Branches

on:
  push:
    branches: ["main"]

  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 2 AM UTC
    
  workflow_dispatch:     # Allow manual run

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dummy step
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: pip install requests

      - name: Run branch cleanup
        run: python cleanup.py
        env:
          GITHUB_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
